"""
Generate Alpha Trader strategy wrappers from the FMZ Quant catalog.

This script reads ``strategies/fmz_catalog.json`` (produced by
``strategies/fmz_parser.py``) and emits a Python module for every strategy
with runnable JavaScript or Python source.  Generated strategies inherit from
``BaseStrategy`` and delegate execution to ``FMZRuntime``.

Usage:
    source venv/bin/activate
    python scripts/generate_fmz_strategies.py

Options:
    --catalog PATH       Path to fmz_catalog.json
    --output-dir PATH    Output directory (default: strategies/generated)
    --batch-size N       Number of strategies per subdirectory (default: 100)
    --status {ok,all}    Generate only parseable strategies or all entries
"""

import argparse
import json
import keyword
import sys
from pathlib import Path
from typing import Any, Dict, List

from loguru import logger

# Ensure project root is importable.
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from strategies.fmz_parser import FMZParser, FMZStrategy, DEFAULT_CATALOG_PATH
from strategies.fmz_runtime import is_quality_fmz_strategy


DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "strategies" / "generated"
BATCH_SIZE = 100


TEMPLATE = '''"""
Auto-generated FMZ Quant strategy wrapper.

Original: {name}
Author: {author}
Source: {source_url}
Language: {language}
Status: {status}

Generated by scripts/generate_fmz_strategies.py — do not edit by hand.
"""

from typing import Any, Dict, List
from datetime import datetime, timedelta
from loguru import logger

from strategies.base import BaseStrategy, Signal
from strategies.fmz_runtime import FMZRuntime, infer_fmz_exchange_name


class {class_name}(BaseStrategy):
    """Auto-generated FMZ Quant strategy wrapper."""

    name = "{identifier}"
    description = {description_repr}
    author = {author_repr}
    source_url = {source_url_repr}
    timeframe = "5m"

    # FMZ strategy arguments
{args_block}

    # Original source metadata
    fmz_language = {language_repr}
    fmz_status = {status_repr}
    fmz_source_code = {source_code_repr}
    fmz_slug = {slug_repr}

    def __init__(self, config: Dict[str, Any] = None):
        super().__init__(config)
        self._args = self._build_args()

    def _build_args(self) -> Dict[str, Any]:
        args = {{}}
{args_populate}
        if self.config:
            args.update(self.config)
        return args

    def generate_signals(self, data: Dict[str, Any]) -> List[Signal]:
        signals = []
        ohlcv = data.get("ohlcv", {{}})
        for symbol, df in ohlcv.items():
            try:
                runtime = FMZRuntime(
                    source_code=self.fmz_source_code,
                    language=self.fmz_language,
                    args=self._args,
                    strategy_name=self.name,
                    timeframe=self.timeframe,
                )
                batch = runtime.run(
                    symbol=symbol,
                    ohlcv_df=df,
                    tick_limit=2,
                    exchange_name=(self.config or {{}}).get("fmz_exchange_name") or infer_fmz_exchange_name(symbol),
                    max_signals=(self.config or {{}}).get("fmz_max_signals", 1),
                )
                signals.extend(batch)
            except Exception as e:
                logger.debug(f"FMZ strategy {{self.name}} failed for {{symbol}}: {{e}}")
        return signals
'''


def _repr_str(value: Any) -> str:
    """Return a repr suitable for embedding in generated source."""
    if value is None:
        return "None"
    if isinstance(value, bool):
        return repr(value)
    if isinstance(value, (int, float)):
        return repr(value)
    return repr(str(value))


def _sanitize_docstring(text: str) -> str:
    """Escape triple quotes and truncate for a docstring."""
    text = (text or "").replace('"""', '"" "')
    lines = text.split("\n")
    summary = lines[0].strip() if lines else ""
    if len(summary) > 200:
        summary = summary[:197] + "..."
    return summary


def _safe_arg_name(name: str) -> str:
    """Sanitize an FMZ argument name to a valid Python identifier."""
    safe = "".join(c if c.isalnum() or c == "_" else "_" for c in name)
    safe = safe.strip("_")
    if not safe:
        safe = "arg"
    if safe[0].isdigit():
        safe = "arg_" + safe
    if keyword.iskeyword(safe):
        safe = safe + "_arg"
    return safe


def _build_args_block(arguments: List[Dict[str, Any]]) -> str:
    lines = []
    for arg in arguments:
        name = arg.get("argument", "")
        default = arg.get("default", "")
        if not name:
            continue
        safe_name = _safe_arg_name(name)
        lines.append(f"    {safe_name} = {_repr_str(default)}")
    if not lines:
        lines.append("    # No strategy arguments defined")
    return "\n".join(lines)


def _build_args_populate(arguments: List[Dict[str, Any]]) -> str:
    lines = []
    for arg in arguments:
        name = arg.get("argument", "")
        if not name:
            continue
        safe_name = _safe_arg_name(name)
        lines.append(f"        args[{_repr_str(name)}] = self.{safe_name}")
    if not lines:
        lines.append("        pass")
    return "\n".join(lines)


def generate_strategy_file(entry: FMZStrategy, output_path: Path) -> None:
    """Write a single generated strategy module."""
    class_name = "".join(
        word.capitalize() for word in entry.python_identifier.split("_") if word
    )
    if not class_name or not class_name[0].isalpha():
        class_name = "FmzStrategy" + class_name

    args_block = _build_args_block(entry.arguments)
    args_populate = _build_args_populate(entry.arguments)

    source = TEMPLATE.format(
        name=entry.name,
        author=entry.author or "Unknown",
        source_url=entry.detail_url or "",
        language=entry.source_language or "unknown",
        status=entry.parse_status,
        class_name=class_name,
        identifier=entry.python_identifier,
        description_summary=_sanitize_docstring(entry.description),
        description_repr=_repr_str(entry.description),
        author_repr=_repr_str(entry.author),
        source_url_repr=_repr_str(entry.detail_url),
        language_repr=_repr_str(entry.source_language),
        status_repr=_repr_str(entry.parse_status),
        source_code_repr=_repr_str(entry.source_code),
        slug_repr=_repr_str(entry.slug),
        args_block=args_block,
        args_populate=args_populate,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(source, encoding="utf-8")


def generate_all(
    catalog_path: Path,
    output_dir: Path,
    batch_size: int,
    status_filter: str,
    quality_only: bool,
) -> int:
    """Generate strategy modules from catalog.  Returns number generated."""
    parser = FMZParser()
    catalog = parser.load_catalog(catalog_path)

    if output_dir.exists():
        # Clean previous generated files to avoid stale wrappers.
        for existing in output_dir.rglob("fmz_*.py"):
            existing.unlink()
        for existing in output_dir.rglob("__init__.py"):
            existing.unlink()

    generated = 0
    entries = []
    for entry in catalog:
        if status_filter == "ok" and entry.parse_status != "ok":
            continue
        if status_filter == "all" and entry.parse_status not in ("ok", "pinescript_only"):
            continue
        if quality_only and not is_quality_fmz_strategy(entry.source_code, entry.description):
            continue
        entries.append(entry)

    for idx, entry in enumerate(entries):
        batch_num = idx // batch_size
        batch_dir = output_dir / f"batch_{batch_num:03d}"
        output_path = batch_dir / f"{entry.python_identifier}.py"
        try:
            generate_strategy_file(entry, output_path)
            generated += 1
        except Exception as e:
            logger.error(f"Failed to generate {entry.slug}: {e}")

    # Write package init files.
    (output_dir / "__init__.py").write_text(
        '"""Auto-generated FMZ strategy wrappers."""\n',
        encoding="utf-8",
    )
    for batch_dir in output_dir.iterdir():
        if batch_dir.is_dir():
            (batch_dir / "__init__.py").write_text(
                '"""Auto-generated FMZ strategy batch."""\n',
                encoding="utf-8",
            )

    logger.info(f"Generated {generated} FMZ strategy wrappers in {output_dir}")
    return generated


def main():
    parser = argparse.ArgumentParser(description="Generate FMZ strategy wrappers")
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG_PATH)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--batch-size", type=int, default=BATCH_SIZE)
    parser.add_argument("--status", choices=["ok", "all"], default="ok")
    parser.add_argument("--quality-only", action="store_true", help="Generate only indicator/rule-based trading strategies")
    args = parser.parse_args()

    generate_all(
        catalog_path=args.catalog,
        output_dir=args.output_dir,
        batch_size=args.batch_size,
        status_filter=args.status,
        quality_only=args.quality_only,
    )


if __name__ == "__main__":
    main()
