"""
PhantomFlow Webhook Signal Parser

Parses TradingView webhook alerts generated by the PhantomFlow indicator
suite and converts them into Alpha Trader TradeIntent objects.

PhantomFlow alerts are discretionary Smart-Money-Concept signals. They are
intentionally mapped to low-conviction TradeIntents so they act as a signal
layer, not an autonomous execution trigger, unless confirmed by other
analysts (TradingView MCP, Unusual Whales, etc.).

Expected webhook payload fields:
    {
        "ticker": "AAPL",
        "price": 150.25,
        "time": "2026-08-19T12:00:00Z",
        "alert": "Phantom Shift Buy",
        "interval": "15m"
    }

Usage:
    from tools.phantomflow_parser import PhantomFlowParser

    parser = PhantomFlowParser(config)
    intent = await parser.parse_webhook(payload)
"""

from datetime import datetime, timedelta
from typing import Any, Dict, Optional

from loguru import logger

from models import ExecutionMode, TradeIntent, TradeStatus, generate_intent_id


class PhantomFlowParser:
    """
    Parser for PhantomFlow TradingView webhook alerts.
    """

    # Mapping of alert substrings to direction and base confidence
    SIGNAL_MAP = {
        "phantom shift buy": ("long", 0.55),
        "phantom shift sell": ("short", 0.55),
        "bos bullish": ("long", 0.50),
        "bos bearish": ("short", 0.50),
        "choch bullish": ("long", 0.52),
        "choch bearish": ("short", 0.52),
        "combo confluence buy": ("long", 0.60),
        "combo confluence sell": ("short", 0.60),
        "order block breakout bullish": ("long", 0.53),
        "order block breakout bearish": ("short", 0.53),
        "fvg bullish": ("long", 0.50),
        "fvg bearish": ("short", 0.50),
        "equal highs": ("short", 0.50),  # liquidity sweep
        "equal lows": ("long", 0.50),
    }

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}
        self.default_venue = self.config.get("phantomflow", {}).get("default_venue", "schwab")
        self.default_size = self.config.get("phantomflow", {}).get("default_size", 10)
        self.require_confirmation = self.config.get("phantomflow", {}).get(
            "require_confirmation", True
        )
        self.base_confidence = self.config.get("phantomflow", {}).get("base_confidence", 0.55)

    async def parse_webhook(self, payload: Dict[str, Any]) -> Optional[TradeIntent]:
        """
        Parse a PhantomFlow webhook payload into a TradeIntent.

        Returns None if the payload cannot be parsed or is not a recognized
        PhantomFlow signal.
        """
        ticker = payload.get("ticker") or payload.get("symbol")
        price_str = payload.get("price") or payload.get("close")
        alert = payload.get("alert") or payload.get("message") or ""

        if not ticker or not alert:
            logger.warning("PhantomFlow: missing ticker or alert in webhook")
            return None

        try:
            price = float(price_str)
        except (TypeError, ValueError):
            logger.warning(f"PhantomFlow: invalid price {price_str}")
            return None

        direction, confidence = self._classify(alert)
        if direction is None:
            logger.warning(f"PhantomFlow: unrecognized alert '{alert}'")
            return None

        # Compute naive stop/target based on ATR proxy (1% of price)
        atr_proxy = price * 0.01
        if direction == "long":
            stop = price - atr_proxy
            target = price + (2 * atr_proxy)
            invalidation = stop
        else:
            stop = price + atr_proxy
            target = price - (2 * atr_proxy)
            invalidation = stop

        execution_mode = ExecutionMode.CONFIRM if self.require_confirmation else ExecutionMode.SIGNAL_ONLY

        return TradeIntent(
            id=generate_intent_id(),
            capsule_id="phantomflow_webhook",
            thesis_id="",
            symbol=ticker.upper(),
            direction=direction,
            entry_price=price,
            stop_price=stop,
            target_price=target,
            conviction=confidence,
            invalidation_price=invalidation,
            time_stop=datetime.utcnow() + timedelta(hours=4),
            risk_reward_ratio=2.0,
            size=self.default_size,
            execution_mode=execution_mode,
            venue=self.default_venue,
            evidence_citations=[],
            status=TradeStatus.PENDING,
            tags=["phantomflow", direction, alert.lower().replace(" ", "_")],
        )

    def _classify(self, alert: str) -> tuple[Optional[str], float]:
        """Classify alert text into direction and confidence."""
        alert_lower = alert.lower()
        best_match = None
        best_confidence = 0.0

        for substring, (direction, confidence) in self.SIGNAL_MAP.items():
            if substring in alert_lower:
                if confidence > best_confidence:
                    best_match = direction
                    best_confidence = confidence

        if best_match:
            return best_match, max(best_confidence, self.base_confidence)
        return None, 0.0
